server:
  port: 9098

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirDevJpa
    username: postgres
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
