server:
  port: 9098

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirDevJpa
    username: postgres
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  server:
    folder: D:\FileUploads\
api:
  jsonplaceholder: https://jsonplaceholder.typicode.com

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG



